### ISSUE TITLE
get_amx_data

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMprospector#6]
Just like there is a `get_gem_data` it would be nice to have a `get_amx_data` to output an annotation matrix  I have a new AnnotatedGEM object with a reduced sample size and it would be nice to easily save that out.

**Comment by biggstd** [comment]
This feature is included, but not yet documented, in the `get_gem_data` function. Passing a list of desired columns to the `annotation_variables` argument should give the desired result.

That is:
```
counts, labels = gsf.get_gem_data(agem, annotation_variables=['class', 'treatment'])
```
